services:
  springboot-todo-service:
    image:  springboot-todo-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  springboot-todo-service
    environment:
      JDK_JAVA_OPTIONS: >
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:+UnlockExperimentalVMOptions -XX:-UseFastUnorderedTimeStamps -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -XX:+PreserveFramePointer
        -XX:StartFlightRecording=settings=myprofile.jfc,maxage=5m,dumponexit=true
#        -XX:NativeMemoryTracking=summary -Xms768m -Xmx768m -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=70
    volumes:
      - ./recordings:/recordings
    ports:
      - 8080:8080
      - 1099:1099
    networks:
      default: null

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    links:
      - springboot-todo-service
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      default: null

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - prometheus
    volumes:
      - ./grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/grafana-all-dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ./grafana/grafana-todo-dashboard.json:/var/lib/grafana/dashboards/grafana-todo-dashboard.json
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
    networks:
      default: null
networks:
  default:
    name: backend
